// Generated by gencpp from file ros_assignment1/Chat.msg
// DO NOT EDIT!


#ifndef ROS_ASSIGNMENT1_MESSAGE_CHAT_H
#define ROS_ASSIGNMENT1_MESSAGE_CHAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <std_msgs/String.h>

namespace ros_assignment1
{
template <class ContainerAllocator>
struct Chat_
{
  typedef Chat_<ContainerAllocator> Type;

  Chat_()
    : header()
    , source_id()
    , message()  {
    }
  Chat_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source_id(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::String_<ContainerAllocator>  _source_id_type;
  _source_id_type source_id;

   typedef  ::std_msgs::String_<ContainerAllocator>  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ros_assignment1::Chat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_assignment1::Chat_<ContainerAllocator> const> ConstPtr;

}; // struct Chat_

typedef ::ros_assignment1::Chat_<std::allocator<void> > Chat;

typedef boost::shared_ptr< ::ros_assignment1::Chat > ChatPtr;
typedef boost::shared_ptr< ::ros_assignment1::Chat const> ChatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_assignment1::Chat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_assignment1::Chat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_assignment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ros_assignment1': ['/home/raysonkoh/Documents/bumble-bee-1/src/ros_assignment1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_assignment1::Chat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_assignment1::Chat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_assignment1::Chat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_assignment1::Chat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_assignment1::Chat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_assignment1::Chat_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_assignment1::Chat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb9c0557da8924b74f97e19e306c3bd5";
  }

  static const char* value(const ::ros_assignment1::Chat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb9c0557da8924b7ULL;
  static const uint64_t static_value2 = 0x4f97e19e306c3bd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_assignment1::Chat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_assignment1/Chat";
  }

  static const char* value(const ::ros_assignment1::Chat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_assignment1::Chat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/String source_id\n"
"std_msgs/String message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::ros_assignment1::Chat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_assignment1::Chat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source_id);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Chat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_assignment1::Chat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_assignment1::Chat_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source_id: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.source_id);
    s << indent << "message: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ASSIGNMENT1_MESSAGE_CHAT_H
